### ISSUE TITLE
Linux - fails to detect yubikey

### ISSUE THREAD

**Issue by dnut** [Yubico/yubioath-flutter#996]
yubioath 5.1.0

When I open the application, it says "Insert your yubikey," instead of detecting the yubikey and listing my TOTP codes. In the menu, the Authenticator button is greyed out and not selectable. The YubiKey button is already selected on startup and nothing changes when it is clicked.

This started happening some time in the past week. I never had this problem before, and have been using my yubikey on this computer with this application for over a year.

The same YubiKey hardware is detected and usable without issue in these three applications:
- YubiKey Personalization Tool
- YubiKey Manager
- Firefox (with U2F authentication)

Dependency versions:

- linux 6.2.2
- yubikey-manager 5.0.1
- pyotherside 1.6.0
- ccid 1.5.2
- pcsclite 1.9.9
- qt5-base 5.15.8
- qt5-declarative 5.15.8
- qt5-quickcontrols 5.15.8
- qt5-quickcontrols2 5.15.8
- qt5-graphicaleffects 5.15.8
- qt5-multimedia 5.15.8

<img src="https://user-images.githubusercontent.com/15116250/223442200-78f6d21a-fabe-418a-bc38-b108b1506017.png" width=50% height=50%><img src="https://user-images.githubusercontent.com/15116250/223441926-1bfdc7b0-d041-4d87-82a7-1639c4508ffb.png" width=50% height=50%>

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qrc:/qml/main.qml:305:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 7. Use 'sequences: [ <key> ]' to bind to all of them.
qrc:/qml/main.qml:297:5: QML Shortcut: Shortcut: Only binding to one of multiple key bindings associated with 9. Use 'sequences: [ <key> ]' to bind to all of them.
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
Qt Quick Layouts: Detected recursive rearrange. Aborting after two iterations.
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"qrc:///py/yubikey.py\", line 23, in <module>\n    from ykman.device import scan_devices, list_all_devices, connect_to_device, get_name, read_info\n\nImportError: cannot import name 'connect_to_device' from 'ykman.device' (/usr/lib/python3.10/site-packages/ykman/device.py)\n"
Unhandled PyOtherSide error: Cannot import module: yubikey (Traceback (most recent call last):

  File "qrc:///py/yubikey.py", line 23, in <module>
    from ykman.device import scan_devices, list_all_devices, connect_to_device, get_name, read_info

ImportError: cannot import name 'connect_to_device' from 'ykman.device' (/usr/lib/python3.10/site-packages/ykman/device.py)
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.init' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.check_descriptors' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
"PyOtherSide error: Traceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n\nNameError: name 'yubikey' is not defined\n"
qml: TypeError: Cannot read property 'success' of undefined undefined
Unhandled PyOtherSide error: Function not found: 'yubikey.controller.is_win_non_admin' (Traceback (most recent call last):

  File "<string>", line 1, in <module>

NameError: name 'yubikey' is not defined
)
qml: TypeError: Cannot read property 'winNonAdmin' of undefined undefined
```

**Comment by dnut** [comment]
Sorry, this is a downstream issue. The arch linux official repos have an outdated version of yubioath-desktop. This is uncharacteristic of arch linux so I hadn't even considered it until after posting this ticket.

https://bugs.archlinux.org/task/77659?project=5&string=yubioath-desktop

**Comment by prochac** [comment]
I do have the same issue.

The problem seems that I have the "official" Arch package installed, which is out of date.
https://archlinux.org/packages/extra/x86_64/yubioath-desktop/

Fixed by uninstalling it, and installing AUR package
https://aur.archlinux.org/packages/yubico-authenticator-bin

**Comment by dnut** [comment]
Yeah, I don't understand why it is still not being updated in the official repos. The package needs a new maintainer or should be moved to the AUR. Anyway, it's not relevant to this repository, which is why I closed the issue.

It is also available in Flathub, which is the solution I went with. Unfortunately, neither the AUR package nor the Flathub package is maintained by Yubico, so you're stuck trusting an anonymous third party, unless you install it directly from https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-latest-linux.tar.gz

**Comment by prochac** [comment]
@dnut Agree, I just left the comment here because it can be helpful to someone else who will struggle with the same issue.

**Comment by JackDinn** [comment]
yes, i have just noticed the same issue, i prefer not not use AUR for security reasons (Manjaro).  Is the extra/yubioath-desktop 5.1.0-3 (5.2 MiB 7.2 MiB) still no good?

**Comment by dnut** [comment]
@JackDinn 

There is a new issue regarding flatpak compatibility with pcsc that I just observed recently. I had pcscd working fine and flatpak configured to allow smart cards, but I still saw the pcscd error in yubico authenticator when it was installed with flatpak. I saw that there is a known issue seen with other distros and apps, so I didn't spend a lot of time trying to figure it out. I just installed the AUR version to fix it on my machine.

**Comment by suntorytimed** [comment]
> > Is the extra/yubioath-desktop 5.1.0-3 (5.2 MiB 7.2 MiB) still no good?
> 
> Yeah it's way out of date. Not sure why the maintainer is not updating it.

At least on openSUSE the issue would be the missing flutter in the official distro repositories. I don't think Manjaro has it in its official repo as well. It's a pain to package such applications without the SDK being available as a dependency. AUR does have the flutter-dev packages available.
